# Kubernetes deployment for the SaintsXCTF API application.
# Author: Andrew Jarombek
# Date: 7/20/2020

apiVersion: apps/v1
kind: Deployment
metadata:
  name: saints-xctf-api-nginx-deployment
  namespace: saints-xctf
  labels:
    version: v1.0.0
    environment: production
    application: saints-xctf-api
    task: nginx
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      version: v1.0.0
      application: saints-xctf-api
      environment: production
      task: nginx
  template:
    metadata:
      labels:
        version: v1.0.0
        environment: production
        application: saints-xctf-api
        task: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - production-applications
      containers:
        - name: saints-xctf-api-nginx
          image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/saints-xctf-api-nginx:1.0.0
          env:
            - name: FLASK_ENV
              value: development
            - name: ENV
              value: dev
          readinessProbe:
            periodSeconds: 5
            initialDelaySeconds: 20
            httpGet:
              path: /
              port: 80
          livenessProbe:
            periodSeconds: 5
            initialDelaySeconds: 20
            failureThreshold: 4
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: saints-xctf-api-flask-deployment
  namespace: saints-xctf
  labels:
    version: v1.0.0
    environment: production
    application: saints-xctf-api
    task: flask
spec:
  replicas: 1
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      version: v1.0.0
      application: saints-xctf-api
      environment: production
      task: flask
  template:
    metadata:
      labels:
        version: v1.0.0
        environment: production
        application: saints-xctf-api
        task: flask
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - production-applications
      containers:
        - name: saints-xctf-api-flask
          image: ${ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/saints-xctf-api-flask:1.0.0
          readinessProbe:
            periodSeconds: 5
            initialDelaySeconds: 20
            tcpSocket:
              port: 5000
          livenessProbe:
            periodSeconds: 5
            initialDelaySeconds: 20
            failureThreshold: 4
            tcpSocket:
              port: 5000
          ports:
            - containerPort: 5000
              protocol: TCP