# Ansible Playbook for my SaintsXCTF AMI
# Author: Andrew Jarombek
# Date: 12/8/2018

- hosts: localhost
  connection: local
  become: yes

  tasks:

    - name: Update APT Packages
      become: yes
      apt:
        update_cache: yes

    - name: Install PHP and Apache
      become: yes
      apt:
        pkg: "{{item}}"
        state: installed
        force: yes
      with_items:
        - git
        - apache2
        - curl
        - php
        - libapache2-mod-php
        - php-mcrypt
        - php-mysql

    - name: Checkout Git Repository
      become: yes
      git:
        repo: https://github.com/AJarombek/saints-xctf.git
        version: master
        dest: ~/git-repo

    - name: Copy Repository to Apache Root Directory
      become: yes
      command: "{{item}}"
      with_items:
        - cp -R ~/git-repo/ /var/www/html/

    - name: Install AWS CLI
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - python --version
        - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
        - python get-pip.py
        - pip --version
        - pip install awscli
        - aws --version

    - name: Install Credential Files
      become: yes
      command: "{{item}}"
      with_items:
        - echo . # TODO

    - name: Configure LAMP
      become: yes
      command: "{{item}}"
      ignore_errors: True
      with_items:
        - echo "ServerName saintsxctf.com" >> /etc/apache2/apache2.conf
        - apache2ctl configtest
        - systemctl restart apache2