# Kubernetes ingress object for the SaintsXCTF database client's ALB ingress controller.
# Author: Andrew Jarombek
# Date: 3/17/2021

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: saints-xctf-database-client-ingress
  namespace: saints-xctf
  annotations:
    kubernetes.io/ingress.class: alb
    external-dns.alpha.kubernetes.io/hostname: db.saintsxctf.com
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: ${ACM_CERT_ARN}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: '/'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/security-groups: ${SECURITY_GROUPS_ID}
    alb.ingress.kubernetes.io/subnets: ${SUBNET_IDS}
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/tags: Name=saints-xctf-database-client-load-balancer,Application=saints-xctf-database-client,Environment=all
  labels:
    version: v1.0.0
    environment: all
    application: saints-xctf-database-client
spec:
  rules:
    - host: db.saintsxctf.com
      http:
        paths:
          - path: /*
            backend:
              serviceName: ssl-redirect
              servicePort: use-annotation
          - path: /*
            backend:
              serviceName: saints-xctf-database-client-service
              servicePort: 80