# Kubernetes NodePort service for the SaintsXCTF database client.
# Author: Andrew Jarombek
# Date: 3/17/2021

apiVersion: v1
kind: Service
metadata:
  name: saints-xctf-database-client-service
  namespace: saints-xctf
  labels:
    version: v1.0.0
    environment: all
    application: saints-xctf-database-client
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    application: saints-xctf-database-client