# GitHub Action for running AWS tests.
# Author: Andrew Jarombek
# Date: 2/22/2023

name: AWS Tests

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main"]

  schedule:
    - cron: "0 5 * * 5"

  workflow_dispatch:

jobs:
  aws_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Job running on a ${{ runner.os }} server"

      - name: Check Out Repository Code
        uses: actions/checkout@v3

      - run: echo "Checked out branch '${{ github.ref }}' of the ${{ github.repository }} repository"

      - name: Install Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Pipenv Dependencies
        run: |
          pip install pipenv
          pipenv install
        working-directory: ./test

      - name: Run AWS Infrastructure Tests
        run: pipenv run test
        working-directory: ./test
        env:
          TEST_ENV: prod
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
